### ISSUE TITLE
Render action params in stimulus_action()

### ISSUE THREAD

**Issue by tacman** [symfony/webpack-encore-bundle#159]
Now that stimulus 3 supports action params (https://world.hey.com/hotwired/stimulus-3-c438d432), the twig function stimulus_action() should render them, such as

```
{{ stimulus_action('item', 'click', 'upvote', {id: 12345, url: '/votes', active: true}) }}

<div data-controller="item">
  <button data-action="item#upvote" 
    data-item-id-param="12345" 
    data-item-url-param="/votes"
    data-item-payload-param='{"value":"1234567"}' 
    data-item-active-param="true">…</button>
</div>
```

I think this would be done similarly to how stimulus_controller handles values, with an optional array.

I also find myself sometimes wanting to pass data- attributes to a target, since stimulus supports getting all targets and walking through them.

**Comment by jmsche** [comment]
Hi @weaverryan,

I was looking at this so I could maybe add this feature (which would be a great addition!).

However I'm not sure how this could be achieved if multiple actions are specified for the same element like this?

```twig
{{ stimulus_action({
 'controller': 'method',
 'other-controller': ['method', {'resize@window': 'onWindowResize'}]
}) }}
```

Do you maybe have an idea of what the syntax would look like when adding parameters to these kind of actions? Or maybe the params could be specified eg. using named parameters? (so the check on 2nd & 3rd args wouldn't trigger)

```twig
{{ stimulus_action({
 'controller': 'method',
 'other-controller': ['method', {'resize@window': 'onWindowResize'}]
}, params={ 'count': 10 }) }}
```

**Comment by weaverryan** [comment]
Yikes! Yea, these functions get ugly with multiples. Logically, I can't think of a way to make this work. Named params is a useful idea... except... which controller's action would the `count: 10` apply to? I think we need to know whether `count: 10` applies to `controller` or `other-controller`, right?

So... what if we "blow up" the syntax. I have 2 idea. This is not specific to action params... it's a new way to specify multiple actions in general, which would make room for parameters like @tacman showed above (except that I think he accidentally swapped the 2nd and 3rd args, but that's not important):

```twig
{{ stimulus_action('item', 'upvote', 'click', {id: 12345, url: '/votes', active: true})|stimulus_action('other-controller', 'other-method') }}
```

The idea would be that `stimulus_action` would ALSO be registered as a filter. The filter would read in the string, reparse it into an array (ok, this is little weird... but really... it should be pretty easy to do), then add the new controller and return the final string.

WDYT? The same could be done for the other functions as well, in theory. And... hmm, I'm not sure if it would break BC, but if we changed `stimulus_action` to return an object with a `Stringable` interface and `__toString()` method... then we could even avoid the "parsing the string back into array" step. We could just put the "information" into this object, and its `__toString()` could then combine that and render it as the string. But, there could also be a `toArray()` method to get the "pieces" back out... or even the `stimulus_action` FILTER would modify this object to add the extra controller info.

This might also relate to #176... where, if we started returning a `Stringable` object, then for the form system, you could do: `stimulus_action('my-controller', 'actionName').toArray()`

P.S.: My 2nd idea is to create a Twig tag - e.g. `{% stimulus_action`. Then we could have whatever custom syntax we want. Tags are hard, so that's something to look into if this idea isn't good or doesn't work.

**Comment by jmsche** [comment]
The first idea, combined with a stringable DTO seems to be a good idea :) And being stringable _should_ not trigger a BC break, but we'll see.

I'm not a fan of chaining the functions+filters but that could be the only way to "easily" handle all this without breaking any existing app.

I'll have a look this month if I can achieve what you described :)
