### ISSUE TITLE
Support for async assets

### ISSUE THREAD

**Issue by Nyholm** [symfony/webpack-encore-bundle#49]
I’m not sure how to implement this or if the bundle even want to support it. But I would like some assets to be loaded asynchronously. 

In the best of all worlds, I would like my base (header, sidebar) css to be loaded sync and the rest could be loaded async. 

———

I’ve taken some inspiration from this YouTube video. https://youtu.be/d5_6yHixpsQ

**Comment by weaverryan** [comment]
It's sort of an ongoing conversation - see #10. Allowing custom attributes would be easy enough, but I want to do it thoughtfully so that we're helping people make the best decision in an easy way (but also allowing people to make *any* decision they want... but perhaps less easily). Our first target was actually http2 preload and maybe prefetch.

**Comment by Nyholm** [comment]
Thank you. I must have missed that issue.
