### ISSUE TITLE
Attempted to load class "GenericLinkProvider" from namespace "Fig\Link". Did you forget a "use" statement for "Symfony\Component\WebLink\GenericLinkProvider"

### ISSUE THREAD

**Issue by sabruss** [symfony/webpack-encore-bundle#83]
**Symfony version(s) affected**:  5

**Description**  
Attempted to load class "GenericLinkProvider" from namespace "Fig\Link". Did you forget a "use" statement for "Symfony\Component\WebLink\GenericLinkProvider"

**How to reproduce** 
create new project symfony/skeleton
`composer req encore`
activate preload

```yaml
webpack_encore:
    preload: true
```
in config/package/webpack_encore.yaml

`composer req web-link` as requested by the bundle

**Possible Solution**  
change namespace from `Fig\Link` to `Symfony\Component\WebLink` in `Symfony\WebpackEncoreBundle\EventListener\PreLoadAssetsEventListener`

**Comment by mbabker** [comment]
It seems like the preload feature is relying on `symfony/web-link` to install `fig/link-utils` (so this bundle is using the FIG package as a transient dependency), but since the WebLink component no longer relies on this package as of 4.4, [this check](https://github.com/symfony/webpack-encore-bundle/blob/8a5ba96bbec60bf04e2a70e45d2e953c94c4edc5/src/DependencyInjection/WebpackEncoreExtension.php#L71-L73) is no longer good enough to protect against turning on an optional feature without all dependencies.

**Comment by stephanvierkant** [comment]
Same problem here, using Symfony 4.4. Installing `composer require fig/link-util` solves it, but shouldn't be required.

@mbabker Small typo: package is called `fig/link-util`, without trailing `s`.

**Comment by weaverryan** [comment]
Fixed in v1.7.2. Thanks for the clear report!
