### ISSUE TITLE
Forward requests - Missing Assets after first forward.

### ISSUE THREAD

**Issue by Warxcell** [symfony/webpack-encore-bundle#94]
I found that https://github.com/symfony/webpack-encore-bundle/blob/master/src/Asset/EntrypointLookup.php#L84-L87
causes 1+N request to don't have assets.

This is my use case:

I have several private page that I need to export as PDF.
Because they are private (needs authentication) - I make several forward request to get generated HTML.
And then pass the generated HTML to service that generates PDF from HTML.

But all pages after first one have broken styles.

**Comment by hktr92** [comment]
same issue happens if you try to render an HTML response in `kernel.exception`. after a few minutes of debugging I've came to the same conclusion as you.

~~as for a solution, I might come up with one after some further experiments.~~

I had to inject `EntrypointLookupInterface` service in my responder and call `reset()` method in order to return the `$newFiles` array. I've seen in #90 to discuss already about this one.

**Comment by Warxcell** [comment]
currently I have this, which resolves the issue:

```
<?php

declare(strict_types=1);

namespace App\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\WebpackEncoreBundle\Asset\EntrypointLookupInterface;

class ResetAssets implements EventSubscriberInterface
{
    private EntrypointLookupInterface $entryLookup;

    public function __construct(EntrypointLookupInterface $entryLookup)
    {
        $this->entryLookup = $entryLookup;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::RESPONSE => 'resetAssets',
        ];
    }

    public function resetAssets(ResponseEvent $event)
    {
        $this->entryLookup->reset();
    }
}
```

But it's better to be fixed in vendor.

**Comment by maxhelias** [comment]
Should be fixed no ?
